### PR TITLE
Fix/travis build

### PR DESCRIPTION
**Pull request by bufferoverflow**

### CODE REVIEW

**Comment by bachp** [comment]
Looks like vendored opnessl doesn't build on windows :(

**Comment by bufferoverflow** [comment]
@bachp rust-embedded/cross removed openssl and provides th eoption to buil dcustom docker images or using old ones, see https://github.com/rust-embedded/cross/issues/229#issuecomment-590546949

**Comment by bachp** [comment]
I was already working on moving CI over to [Github Actions](https://github.com/bachp/git-mirror/tree/github-actions) but I never got to finish the release part. Maybe it's time to finish that.

**Comment by bufferoverflow** [comment]
@bachp ok, so I close this one

**Pull request closed without merging**
